/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "lkk",
  "description": "Just playing around",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "author",
        "content": "vuepress介绍 lkk"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "vuepress介绍 lkk"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-5d457836",
      "path": "/",
      "lastUpdated": "2022年5月15日星期日下午5点02分",
      "lastUpdatedTimestamp": 1652605361000,
      "createdTime": 1652451650000
    },
    {
      "title": "一级标题",
      "frontmatter": {},
      "regularPath": "/about/one.html",
      "relativePath": "about/one.md",
      "key": "v-273b0249",
      "path": "/about/one.html",
      "headers": [
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题"
        },
        {
          "level": 3,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-2"
        },
        {
          "level": 3,
          "title": "二级标题",
          "slug": "二级标题-2"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-3"
        },
        {
          "level": 3,
          "title": "二级标题",
          "slug": "二级标题-3"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-4"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-5"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-6"
        }
      ],
      "lastUpdated": "2022年5月13日星期五晚上10点20分",
      "lastUpdatedTimestamp": 1652451650000,
      "createdTime": 1652451650000
    },
    {
      "title": "关于我",
      "frontmatter": {
        "navbar": false
      },
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-c6f285d4",
      "path": "/about/",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题"
        },
        {
          "level": 3,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-2"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-3"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-4"
        }
      ],
      "lastUpdated": "2022年5月13日星期五晚上10点20分",
      "lastUpdatedTimestamp": 1652451650000,
      "createdTime": 1652451650000
    },
    {
      "title": "关于我",
      "frontmatter": {},
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-ca873794",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        }
      ],
      "lastUpdated": "2022年5月17日星期二晚上10点20分",
      "lastUpdatedTimestamp": 1652797252000,
      "createdTime": 1652451650000
    },
    {
      "frontmatter": {},
      "regularPath": "/test/",
      "relativePath": "test/README.md",
      "key": "v-5c0d5a70",
      "path": "/test/",
      "lastUpdated": "2022年5月13日星期五晚上10点20分",
      "lastUpdatedTimestamp": 1652451650000,
      "createdTime": 1652451650000
    },
    {
      "title": "2004-人民币面临巨大的贬值压力",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "'",
        "7": "2",
        "8": "0",
        "9": "0",
        "10": "4",
        "11": "-",
        "12": "人",
        "13": "民",
        "14": "币",
        "15": "面",
        "16": "临",
        "17": "巨",
        "18": "大",
        "19": "的",
        "20": "贬",
        "21": "值",
        "22": "压",
        "23": "力",
        "24": "'"
      },
      "regularPath": "/test/test.html",
      "relativePath": "test/test.md",
      "key": "v-eb26723a",
      "path": "/test/test.html",
      "headers": [
        {
          "level": 2,
          "title": "2004-人民币面临巨大的贬值压力",
          "slug": "_2004-人民币面临巨大的贬值压力"
        }
      ],
      "lastUpdated": "2022年5月18日星期三下午4点12分",
      "lastUpdatedTimestamp": 1652861529000,
      "createdTime": 1652861529000
    },
    {
      "title": "一级标题",
      "frontmatter": {},
      "regularPath": "/about/two.html",
      "relativePath": "about/two.md",
      "key": "v-efc2d6ee",
      "path": "/about/two.html",
      "headers": [
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题"
        },
        {
          "level": 3,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题"
        },
        {
          "level": 3,
          "title": "二级标题",
          "slug": "二级标题-2"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题-2"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-2"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-3"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-4"
        }
      ],
      "lastUpdated": "2022年5月13日星期五晚上10点20分",
      "lastUpdatedTimestamp": 1652451650000,
      "createdTime": 1652451650000
    },
    {
      "title": "一级标题",
      "frontmatter": {},
      "regularPath": "/test/test1.html",
      "relativePath": "test/test1.md",
      "key": "v-5aa9402b",
      "path": "/test/test1.html",
      "headers": [
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题"
        },
        {
          "level": 3,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-2"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-3"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-4"
        }
      ],
      "lastUpdated": "2022年5月17日星期二晚上10点20分",
      "lastUpdatedTimestamp": 1652797252000,
      "createdTime": 1652451650000
    },
    {
      "title": "一级标题",
      "frontmatter": {},
      "regularPath": "/test/test2.html",
      "relativePath": "test/test2.md",
      "key": "v-43ffef29",
      "path": "/test/test2.html",
      "headers": [
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题"
        },
        {
          "level": 3,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-2"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-3"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-4"
        }
      ],
      "lastUpdated": "2022年5月13日星期五晚上10点20分",
      "lastUpdatedTimestamp": 1652451650000,
      "createdTime": 1652451650000
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/tim.jpg",
    "lastUpdated": "更新时间",
    "sidebar": [
      "/",
      "/about",
      {
        "title": "美丽的test",
        "path": "/test/",
        "collapsable": false,
        "sidebarDepth": 2,
        "children": [
          "/test/test",
          "/test/test1",
          "/test/test2"
        ]
      }
    ],
    "sidebarDepth": 3,
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "导航",
        "link": "/about.html"
      },
      {
        "text": "经济",
        "link": "/test/"
      },
      {
        "text": "博客地址",
        "items": [
          {
            "text": "Github",
            "link": "https://github.com/zhangwinwin/FEBlog"
          },
          {
            "text": "掘金",
            "link": "https://juejin.cn/user/1486195453331757"
          },
          {
            "text": "语言",
            "items": [
              {
                "text": "Chinese",
                "link": ""
              },
              {
                "text": "English",
                "link": ""
              },
              {
                "text": "Japanese",
                "link": ""
              }
            ]
          }
        ]
      }
    ]
  }
}